### ISSUE TITLE
Status Conditions Metrics should be per-object type 

### ISSUE THREAD

**Issue by njtran** [awslabs/operatorpkg#87]
Status Conditions currently include the type of the object as a dimension of the metric. Metric aggregations are usually done on a metric name and aggregated based on the dimensions of the metric. If I wanted to say get the number of nodes for label `team: app-a` that have a MemoryPressure status condition, I can't do it with the given status conditions. I'd have to cross reference each of the status conditions, with a metric on the node for labels, and then aggregate them, which has odd aggregation behavior as there's not a 1-1 for each metric, having to do joins.

Ideally, we can just auto-gen metrics in the `operator_status` system and add a subsystem with the type of the object we're emitting for, and do the usual status condition metrics with specific labels we care about added in.

**Comment by jonathan-innis** [comment]
Closed by #98
